FROM registry.gitlab.com/leonardmessier/shef/shef-x11:1.0.0

ARG USERNAME
COPY --chown=linuxbrew:linuxbrew ./ /home/${USERNAME}/.config/shef/recipes/zsh-recipe
WORKDIR /home/${USERNAME}/.config/shef/recipes/zsh-recipe

RUN shef install-recipe


